- action: detect_version executable=influx option=--version pattern="InfluxDB shell ([\d.]+)"

- block:
  - get_url:
      url: "{{ influxdb_download_urls[ansible_os_family] }}"
      dest: /tmp/
    register: influxdb_download

  - block:
    - apt:
        deb: "{{ influxdb_download['dest'] }}"
        update_cache: no
        state: present
    when: ansible_os_family == 'Debian'

  - block:
    - yum:
        name: "{{ influxdb_download['dest'] }}"
        update_cache: no
        state: present
    when: ansible_os_family == 'RedHat'

  - service:
      name: influxdb
      state: started
  become: true
  become_user: root
  when: not influx.installed or influx.version != influxdb_version
