influxdb_host: localhost

telegraf_version: 0.10.4.1

telegraf_download_urls:
  Debian: "http://get.influxdb.org/telegraf/telegraf_0.10.4.1-1_amd64.deb"
  RedHat: "http://get.influxdb.org/telegraf/telegraf-0.10.4.1-1.x86_64.rpm"
