- hosts: all
  pre_tasks:
    - debug: var=hostvars[inventory_hostname]

  pre_tasks:
    - apt: name=couchdb state=latest
      become: true
      become_user: root

  roles:
    - influxdb
    - telegraf
    - chronograf
    - telegraf.couchdb
    - telegraf.docker

  post_tasks:
    # todo output: influxdb
    # todo input: couchdb

